name: CryoREAD
channels:
  - pytorch
  - nvidia
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - cudatoolkit=11.1.74
  - pip=21.1.3
  - python=3.8.10
  - pytorch=1.9.0
  - pip:
      - biopython
      - numba==0.57.1
      - numpy==1.24.4
      - scipy==1.10.1
      - tqdm==4.65.0
      - ortools==9.4.1874
      - mrcfile
      - progress
      - numba-progress
